config/routes.rb
Rails.application.routes.draw do
  get '/admin' => 'admin#index'
  put '/admin/:id'  => 'admin#update'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  resources :apartments
  root 'apartments#index'

end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  belongs_to :user
  geocoded_by :address
  after_validation :geocode
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment :image, presence: true,
    content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] },
    size: { in: 0..10.megabytes }
  resourcify
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :authenticate_user!, :set_apartment, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /apartments
  # GET /apartments.json
  def index
    @apartments = Apartment.all
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
  end

  # GET /apartments/new
  def new
    @apartment = Apartment.new
  end

  # GET /apartments/1/edit
  def edit
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @apartments = Apartment.find(params[:id])
    @hash = Gmaps4rails.build_markers(@apartments) do |apartment, marker|
      marker.lat apartment.latitude
      marker.lng apartment.longitude
    end
end
  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:latitude, :longitude, :address, :name, :contact, :image)
    end

end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/views/apartments/_form.html.erb
<%= form_for(@apartment, :html => { :multipart => true }) do |f| %>
  <% if @apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
      <% @apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :contact %><br>
    <%= f.text_field :contact %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<h1>Editing Apartment</h1>

<%= render 'form' %>

<%= link_to 'Show', @apartment %> |
<%= link_to 'Back', apartments_path %>

app/views/apartments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Apartments</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Address</th>
      <th>Name</th>
      <th>Contact</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.latitude %></td>
        <td><%= apartment.longitude %></td>
        <td><%= apartment.address %></td>
        <td><%= apartment.name %></td>
        <td><%= apartment.contact %></td>
        <td><%= link_to 'Show', apartment %></td>
        <td><%= link_to 'Edit', edit_apartment_path(apartment) %></td>
        <td><%= link_to 'Destroy', apartment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Apartment', new_apartment_path %>

app/views/apartments/new.html.erb
<h1>New Apartment</h1>

<%= render 'form' %>

<%= link_to 'Back', apartments_path %>

app/views/apartments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= link_to image_tag(@apartment.image.url(:large)), @apartment.image.url %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @apartment.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @apartment.longitude %>
</p>

<p>
  <strong>Address:</strong>
  <%= @apartment.address %>
</p>

<p>
  <strong>Name:</strong>
  <%= @apartment.name %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @apartment.contact %>
</p>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({
    provider: {},
    internal: {
      id: 'map'
    }
  },
  function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMaps().setZoom(12);
  }
);
</script>

<!-- <script>
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
</script> -->

<%= link_to 'Edit', edit_apartment_path(@apartment) %> |
<%= link_to 'Back', apartments_path %>